version: '3.9'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    volumes:
      - './data:/data'
    ports:
      - 25565:25565
    environment:
      SERVER_NAME: "tenebris server"
      EULA: "TRUE"
      TYPE: "PURPUR"
      ANNOUNCE_PLAYER_ACHIEVMENTS: "TRUE"
      EXEC_DIRECTLY: "TRUE"
      MAX_PLAYERS: 10
      MOTD: "§lTenebris §nprivate §rtemplate"
    tty: true
    stdin_open: true
    restart: unless-stopped

